### ISSUE TITLE
Decide between `iced` and `egui`

### ISSUE THREAD

**Issue by pbelokon** [pbelokon/termionus#13]
Compare the two libraries to decide which one is actually easier to use. 
I would like to file the following things we need to figure out: 
- API ease of use
- Benefits

**Comment by JerryHue** [comment]
I think the most important aspect is the GUI mode that `iced` and `egui` implement.

`iced` implements [retained GUI mode](https://en.wikipedia.org/wiki/Retained_mode), while `egui` implements [immediate GUI mode](https://en.wikipedia.org/wiki/Immediate_mode_GUI).

If I am understanding correctly, immediate GUI mode gives you more control on the order of rendering, and you essentially build the model of the screen, just passing to the library so that the library can actually render. This is like creating a game with SDL. If you want to know more about the advantages and disadvantages of immediate mode, check [this](https://github.com/emilk/egui#why-immediate-mode).

With retained GUI mode, the library is in charge of explicitly building the model, and the only thing that you do is to declare to the library what you want (not how!), and you would pass callbacks that handle specific events.

In my opinion, I would prefer to go with the immediate mode, since it gives you more power in organising your layout and the like.

**Comment by pbelokon** [comment]
I would agree with you on that one I prefer  immediate mode, also I think for me egui looks much more readable.

**Comment by pbelokon** [comment]
@JerryHue  can you  close issue #12 and open a new one for setting up egui
